import type { FacilityResource } from "@/domain/resources"

const timestamp = "2026-08-01T09:00:00.000Z"

export const initialMockResources: FacilityResource[] = [
  {
    id: "resource-room-merkez-atlas",
    type: "ROOM",
    name: "Atlas Toplantı Odası",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-room-arge-pusula",
    type: "ROOM",
    name: "Pusula Toplantı Odası",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-arge",
    facilityName: "Ar-Ge Merkezi",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-notebook-merkez",
    type: "POOLED_EQUIPMENT",
    name: "Notebook Havuzu",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    totalQuantity: 12,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-projector-otomotiv",
    type: "POOLED_EQUIPMENT",
    name: "Projektör Havuzu",
    companyId: "bplas-otomotiv",
    companyName: "BPLAS Otomotiv A.Ş.",
    facilityId: "otomotiv-uretim",
    facilityName: "Üretim Tesisi",
    totalQuantity: 4,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-projector-arge",
    type: "POOLED_EQUIPMENT",
    name: "Taşınabilir Projektör Havuzu",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-arge",
    facilityName: "Ar-Ge Merkezi",
    totalQuantity: 2,
    isActive: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
]
