import type { FacilityResource } from "@/domain/resources"

const timestamp = "2026-08-01T09:00:00.000Z"

export const initialMockResources: FacilityResource[] = [
  {
    id: "resource-room-merkez-atlas",
    type: "ROOM",
    name: "Atlas Toplantı Odası",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-room-arge-pusula",
    type: "ROOM",
    name: "Pusula Toplantı Odası",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-arge",
    facilityName: "Ar-Ge Merkezi",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-notebook-merkez",
    type: "POOLED_EQUIPMENT",
    name: "Notebook Havuzu",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    totalQuantity: 12,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-projector-otomotiv",
    type: "POOLED_EQUIPMENT",
    name: "Projektör Havuzu",
    companyId: "bplas-otomotiv",
    companyName: "BPLAS Otomotiv A.Ş.",
    facilityId: "otomotiv-uretim",
    facilityName: "Üretim Tesisi",
    totalQuantity: 4,
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-projector-arge",
    type: "POOLED_EQUIPMENT",
    name: "Taşınabilir Projektör Havuzu",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-arge",
    facilityName: "Ar-Ge Merkezi",
    totalQuantity: 2,
    isActive: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-transit-merkez",
    type: "VEHICLE",
    brand: "Ford",
    model: "Transit",
    licensePlate: "16 BPL 101",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-megane-otomotiv",
    type: "VEHICLE",
    brand: "Renault",
    model: "Megane",
    licensePlate: "16 BPL 202",
    companyId: "bplas-otomotiv",
    companyName: "BPLAS Otomotiv A.Ş.",
    facilityId: "otomotiv-uretim",
    facilityName: "Üretim Tesisi",
    isActive: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-sprinter-merkez",
    type: "VEHICLE",
    brand: "Mercedes",
    model: "Sprinter",
    licensePlate: "16 BPL 303",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-courier-merkez",
    type: "VEHICLE",
    brand: "Ford",
    model: "Courier",
    licensePlate: "16 BPL 404",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-daily-merkez",
    type: "VEHICLE",
    brand: "Iveco",
    model: "Daily",
    licensePlate: "16 BPL 606",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-kangoo-merkez",
    type: "VEHICLE",
    brand: "Renault",
    model: "Kangoo",
    licensePlate: "16 BPL 707",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-doblo-merkez",
    type: "VEHICLE",
    brand: "Fiat",
    model: "Doblo",
    licensePlate: "16 BPL 808",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-master-merkez",
    type: "VEHICLE",
    brand: "Renault",
    model: "Master",
    licensePlate: "16 BPL 818",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-transporter-arge",
    type: "VEHICLE",
    brand: "Volkswagen",
    model: "Transporter Uzun Şasi",
    licensePlate: "16 BPL 919",
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-arge",
    facilityName: "Ar-Ge Merkezi",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-vehicle-proace-otomotiv",
    type: "VEHICLE",
    brand: "Toyota",
    model: "Proace",
    licensePlate: "16 BPL 515",
    companyId: "bplas-otomotiv",
    companyName: "BPLAS Otomotiv A.Ş.",
    facilityId: "otomotiv-uretim",
    facilityName: "Üretim Tesisi",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-ayse-demir",
    type: "DRIVER",
    fullName: "Ayşe Demir",
    licenseClasses: ["B", "C"],
    documents: ["SRC2", "Psikoteknik"],
    canDriveCommercialVehicles: true,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-mehmet-kaya",
    type: "DRIVER",
    fullName: "Mehmet Kaya",
    licenseClasses: ["B"],
    documents: [],
    canDriveCommercialVehicles: false,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-arge",
    facilityName: "Ar-Ge Merkezi",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-zeynep-arslan",
    type: "DRIVER",
    fullName: "Zeynep Arslan",
    licenseClasses: ["B", "C"],
    documents: ["SRC2"],
    canDriveCommercialVehicles: true,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-burak-cetin",
    type: "DRIVER",
    fullName: "Burak Çetin",
    licenseClasses: ["B"],
    documents: ["Psikoteknik"],
    canDriveCommercialVehicles: false,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-selin-yildiz",
    type: "DRIVER",
    fullName: "Selin Yıldız",
    licenseClasses: ["B", "C"],
    documents: ["SRC2", "Psikoteknik"],
    canDriveCommercialVehicles: true,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-emre-aksoy",
    type: "DRIVER",
    fullName: "Emre Aksoy",
    licenseClasses: ["B"],
    documents: ["SRC2"],
    canDriveCommercialVehicles: true,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-hakan-yalcin",
    type: "DRIVER",
    fullName: "Hakan Yalçın",
    licenseClasses: ["B", "C"],
    documents: ["SRC2", "Psikoteknik"],
    canDriveCommercialVehicles: true,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-elif-sahin",
    type: "DRIVER",
    fullName: "Elif Şahin",
    licenseClasses: ["B", "C"],
    documents: ["SRC2"],
    canDriveCommercialVehicles: true,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-merkez",
    facilityName: "Merkez Tesis",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-can-ozdemir",
    type: "DRIVER",
    fullName: "Can Özdemir",
    licenseClasses: ["B"],
    documents: ["Psikoteknik"],
    canDriveCommercialVehicles: false,
    companyId: "bplas",
    companyName: "BPLAS A.Ş.",
    facilityId: "bplas-arge",
    facilityName: "Ar-Ge Merkezi",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "resource-driver-deniz-gok",
    type: "DRIVER",
    fullName: "Deniz Gök",
    licenseClasses: ["B", "C"],
    documents: ["SRC2", "SRC4", "Psikoteknik"],
    canDriveCommercialVehicles: true,
    companyId: "bplas-otomotiv",
    companyName: "BPLAS Otomotiv A.Ş.",
    facilityId: "otomotiv-uretim",
    facilityName: "Üretim Tesisi",
    isActive: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
]
