import { addHours, format, startOfDay, subDays } from "date-fns"
import type { GoodsMovement } from "@/domain/goods-movements"

const today = startOfDay(new Date())
export const initialMockGoodsMovements: GoodsMovement[] = [
  { id: "goods-101", direction: "INBOUND", companyId: "bplas", companyName: "BPLAS A.Ş.", facilityId: "bplas-merkez", facilityName: "Merkez Tesis", counterpartyName: "Kuzey Ambalaj", plannedDate: format(today, "yyyy-MM-dd"), plannedTime: "09:00", goodsDescription: "Ambalaj malzemesi", referenceNumber: "IRS-2026-101", status: "PLANNED", createdAt: today.toISOString() },
  { id: "goods-102", direction: "OUTBOUND", companyId: "bplas", companyName: "BPLAS A.Ş.", facilityId: "bplas-merkez", facilityName: "Merkez Tesis", counterpartyName: "Ege Endüstri", plannedDate: format(today, "yyyy-MM-dd"), plannedTime: "12:00", goodsDescription: "Numune sevkiyatı", status: "PLANNED", createdAt: today.toISOString() },
  { id: "goods-103", direction: "INBOUND", companyId: "bplas-otomotiv", companyName: "BPLAS Otomotiv A.Ş.", facilityId: "otomotiv-uretim", facilityName: "Üretim Tesisi", counterpartyName: "Mavi Kimya", plannedDate: format(today, "yyyy-MM-dd"), plannedTime: "16:00", goodsDescription: "Hammadde", status: "PLANNED", createdAt: today.toISOString() },
  { id: "goods-104", direction: "OUTBOUND", companyId: "bplas", companyName: "BPLAS A.Ş.", facilityId: "bplas-arge", facilityName: "Ar-Ge Merkezi", counterpartyName: "Atlas Lojistik", plannedDate: format(today, "yyyy-MM-dd"), goodsDescription: "Test parçası", status: "COMPLETED", actualAt: addHours(today, -1).toISOString(), actualPlate: "16 BPL 908", actualDriverName: "Mert Kaya", createdAt: today.toISOString() },
  { id: "goods-105", direction: "INBOUND", companyId: "bplas", companyName: "BPLAS A.Ş.", facilityId: "bplas-arge", facilityName: "Ar-Ge Merkezi", counterpartyName: "Tekno Servis", plannedDate: format(subDays(today, 1), "yyyy-MM-dd"), plannedTime: "14:30", goodsDescription: "Teknik ekipman", status: "PLANNED", createdAt: today.toISOString() },
  { id: "goods-106", direction: "OUTBOUND", companyId: "bplas-otomotiv", companyName: "BPLAS Otomotiv A.Ş.", facilityId: "otomotiv-uretim", facilityName: "Üretim Tesisi", counterpartyName: "Marmara Otomotiv", plannedDate: format(addHours(today, 24), "yyyy-MM-dd"), plannedTime: "10:30", goodsDescription: "Yedek parça", referenceNumber: "IRS-2026-106", status: "PLANNED", createdAt: today.toISOString() },
  { id: "goods-107", direction: "INBOUND", companyId: "anadolu-lojistik", companyName: "Anadolu Lojistik A.Ş.", facilityId: "anadolu-lojistik-merkez", facilityName: "Lojistik Merkezi", counterpartyName: "Doğu Palet", plannedDate: format(today, "yyyy-MM-dd"), goodsDescription: "Paletli ürün", status: "PLANNED", createdAt: today.toISOString() },
  { id: "goods-108", direction: "OUTBOUND", companyId: "anadolu-lojistik", companyName: "Anadolu Lojistik A.Ş.", facilityId: "anadolu-lojistik-merkez", facilityName: "Lojistik Merkezi", counterpartyName: "Güney Dağıtım", plannedDate: format(subDays(today, 1), "yyyy-MM-dd"), plannedTime: "16:00", goodsDescription: "İade sevkiyatı", status: "COMPLETED", actualAt: addHours(today, -3).toISOString(), actualPlate: "34 ANL 410", actualDriverName: "Kerem Yıldız", createdAt: today.toISOString() },
  { id: "goods-109", direction: "INBOUND", companyId: "bplas", companyName: "BPLAS A.Ş.", facilityId: "bplas-merkez", facilityName: "Merkez Tesis", counterpartyName: "Ofis Tedarik", plannedDate: format(subDays(today, 1), "yyyy-MM-dd"), plannedTime: "08:30", goodsDescription: "Ofis sarf malzemesi", status: "CANCELLED", note: "Sevkiyat iptal edildi.", createdAt: today.toISOString() },
  { id: "goods-110", direction: "OUTBOUND", companyId: "bplas", companyName: "BPLAS A.Ş.", facilityId: "bplas-arge", facilityName: "Ar-Ge Merkezi", counterpartyName: "Batı Laboratuvar", plannedDate: format(subDays(today, 2), "yyyy-MM-dd"), plannedTime: "11:00", goodsDescription: "Numune seti", status: "COMPLETED", actualAt: addHours(today, -24).toISOString(), actualPlate: "16 BPL 527", actualDriverName: "Mert Kaya", createdAt: today.toISOString() },
]
