import { Plus, Save } from "lucide-react"
import { useEffect, useState } from "react"

import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { visitorCardStatusLabels, visitorCardStatuses, type OperationalSettings, type VisitTypeDefinition, type VisitorCardInventoryItem } from "@/domain/admin"
import { canTransitionVisitorCard, isOperationalSettingsValid } from "@/features/admin/admin-utils"
import { useAdmin } from "@/features/admin/admin-context"
import { formatTr } from "@/lib/date"
import { adminService } from "@/services"

type Tab = "types" | "cards" | "rules" | "operations"
const tabs: { id: Tab; label: string }[] = [{ id: "types", label: "Ziyaret Türleri" }, { id: "cards", label: "Ziyaretçi Kartları" }, { id: "rules", label: "Ziyaretçi Kuralları" }, { id: "operations", label: "Operasyon Parametreleri" }]

export function SystemSettingsPage() {
  const { visitTypes, visitorCards, visitorRules, settings, reload } = useAdmin()
  const [tab, setTab] = useState<Tab>("types")
  const [visitType, setVisitType] = useState<VisitTypeDefinition | null>(null)
  const [card, setCard] = useState<VisitorCardInventoryItem | null>(null)
  const [rulesOpen, setRulesOpen] = useState(false)
  const [settingsDraft, setSettingsDraft] = useState<OperationalSettings | null>(settings)
  useEffect(() => setSettingsDraft(settings), [settings])
  return <div className="-mt-2.5 -mb-2.5 flex min-h-[111.112dvh] min-w-0 flex-col gap-3 pt-[11px] pb-[14px] md:-mt-3 md:-mb-3"><section className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border bg-card shadow-panel"><div className="flex shrink-0 gap-1 overflow-x-auto border-b px-2 pt-2" role="tablist" aria-label="Sistem ayarları sekmeleri">{tabs.map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)} className={tab === item.id ? "border-b-2 border-blue-600 px-3 py-2 text-xs font-semibold text-blue-700" : "px-3 py-2 text-xs font-medium text-slate-600 hover:text-slate-900"}>{item.label}</button>)}</div><div className="min-h-0 flex-1 overflow-auto p-3">{tab === "types" && <VisitTypesPanel items={visitTypes} onEdit={setVisitType} />}{tab === "cards" && <CardsPanel items={visitorCards} onEdit={setCard} />}{tab === "rules" && <RulesPanel items={visitorRules} onNew={() => setRulesOpen(true)} />}{tab === "operations" && <OperationsPanel value={settingsDraft} onChange={setSettingsDraft} />}</div>{tab === "operations" && <div className="flex justify-end border-t p-2.5"><Button size="sm" disabled={!settingsDraft || !isOperationalSettingsValid(settingsDraft)} onClick={async () => { if (!settingsDraft) return; await adminService.saveOperationalSettings(settingsDraft); await reload() }}><Save />Kaydet</Button></div>}</section><VisitTypeDialog entity={visitType} onOpenChange={(open) => !open && setVisitType(null)} onSaved={() => void reload()} /><CardDialog entity={card} onOpenChange={(open) => !open && setCard(null)} onSaved={() => void reload()} /><RuleDialog open={rulesOpen} onOpenChange={setRulesOpen} onSaved={() => void reload()} /></div>
}

function VisitTypesPanel({ items, onEdit }: { items: VisitTypeDefinition[]; onEdit(item: VisitTypeDefinition): void }) { return <PanelHeader action={() => onEdit({ id: "", name: "", active: true })} actionLabel="Ziyaret türü ekle"><table className="w-full min-w-[460px] text-xs"><thead className="border-b bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-2 text-left">Tanım</th><th className="px-3 py-2 text-left">Durum</th><th /></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-3 py-3 font-medium">{item.name}</td><td className="px-3">{item.active ? "Aktif" : "Pasif"}</td><td className="px-3 text-right"><Button variant="ghost" size="sm" onClick={() => onEdit(item)}>Düzenle</Button></td></tr>)}</tbody></table></PanelHeader> }
function CardsPanel({ items, onEdit }: { items: VisitorCardInventoryItem[]; onEdit(item: VisitorCardInventoryItem): void }) { return <PanelHeader action={() => onEdit({ id: "", cardNumber: "", status: "AVAILABLE" })} actionLabel="Kart tanımla"><table className="w-full min-w-[520px] text-xs"><thead className="border-b bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-2 text-left">Kart no</th><th className="px-3 py-2 text-left">Durum</th><th className="px-3 py-2 text-left">Kullanım bilgisi</th><th /></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-3 py-3 font-semibold">{item.cardNumber}</td><td className="px-3">{visitorCardStatusLabels[item.status]}</td><td className="px-3">{item.assignedVisitorName ?? "—"}</td><td className="px-3 text-right"><Button variant="ghost" size="sm" onClick={() => onEdit(item)}>Yönet</Button></td></tr>)}</tbody></table></PanelHeader> }
function RulesPanel({ items, onNew }: { items: ReturnType<typeof useAdmin>["visitorRules"]; onNew(): void }) { const active = items.find((item) => item.active); return <PanelHeader action={onNew} actionLabel="Yeni versiyon"><div className="grid gap-3 lg:grid-cols-[minmax(0,1.2fr)_minmax(280px,.8fr)]">{active && <article className="rounded-md border bg-slate-50 p-3"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Aktif versiyon v{active.version}</h2><span className="text-[11px] text-slate-500">{formatTr(new Date(active.publishedAt), "d MMM yyyy")}</span></div><p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-slate-700">{active.content}</p></article>}<div className="rounded-md border"><h2 className="border-b px-3 py-2 text-xs font-semibold">Geçmiş versiyonlar</h2>{items.filter((item) => !item.active).map((item) => <details key={item.id} className="border-b last:border-b-0"><summary className="cursor-pointer px-3 py-2 text-xs font-medium">v{item.version} · {formatTr(new Date(item.publishedAt), "d MMM yyyy")}</summary><p className="whitespace-pre-wrap px-3 pb-3 text-xs text-slate-600">{item.content}</p></details>)}</div></div></PanelHeader> }
function OperationsPanel({ value, onChange }: { value: OperationalSettings | null; onChange(value: OperationalSettings): void }) { if (!value) return null; return <div className="max-w-lg space-y-3"><label><span className="mb-1 block text-xs font-medium">Ziyaret gecikme toleransı (dakika)</span><Input type="number" min="0" value={value.overdueToleranceMinutes} onChange={(event) => onChange({ ...value, overdueToleranceMinutes: Number(event.target.value) })} /></label><label><span className="mb-1 block text-xs font-medium">Security overdue uyarı tekrar aralığı (dakika)</span><Input type="number" min="1" value={value.overdueAlertRepeatMinutes} onChange={(event) => onChange({ ...value, overdueAlertRepeatMinutes: Number(event.target.value) })} /></label></div> }
function PanelHeader({ children, action, actionLabel }: { children: React.ReactNode; action(): void; actionLabel: string }) { return <div><div className="mb-3 flex justify-end"><Button size="sm" onClick={action}><Plus />{actionLabel}</Button></div><div className="overflow-x-auto rounded-md border">{children}</div></div> }

function VisitTypeDialog({ entity, onOpenChange, onSaved }: { entity: VisitTypeDefinition | null; onOpenChange(open: boolean): void; onSaved(): void }) { const [draft, setDraft] = useState<VisitTypeDefinition | null>(null); const value = draft && entity && draft.id === entity.id ? draft : entity; const save = async () => { if (!value?.name.trim()) return; await adminService.saveVisitType(value); setDraft(null); onSaved(); onOpenChange(false) }; return <Dialog open={Boolean(entity)} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Ziyaret türü</DialogTitle></DialogHeader>{value && <><label><span className="mb-1 block text-xs font-medium">Ad</span><Input autoFocus value={value.name} onChange={(event) => setDraft({ ...value, name: event.target.value })} /></label><label className="flex items-center gap-2 text-xs font-medium"><input type="checkbox" checked={value.active} onChange={(event) => setDraft({ ...value, active: event.target.checked })} />Aktif</label></>}<DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>İptal</Button><Button onClick={() => void save()}>Kaydet</Button></DialogFooter></DialogContent></Dialog> }
function CardDialog({ entity, onOpenChange, onSaved }: { entity: VisitorCardInventoryItem | null; onOpenChange(open: boolean): void; onSaved(): void }) { const [draft, setDraft] = useState<VisitorCardInventoryItem | null>(null); const [error, setError] = useState(""); const value = draft && entity && draft.id === entity.id ? draft : entity; const save = async () => { if (!value?.cardNumber.trim()) return; try { if (value.id) { if (!canTransitionVisitorCard(entity!.status, value.status)) throw new Error("Kullanımdaki kart sadece Security operasyonu ile değiştirilebilir."); await adminService.changeVisitorCardStatus(value.id, value.status) } else await adminService.saveVisitorCard(value); setDraft(null); onSaved(); onOpenChange(false) } catch (reason) { setError(reason instanceof Error ? reason.message : "Kart güncellenemedi.") } }; return <Dialog open={Boolean(entity)} onOpenChange={(open) => { setError(""); onOpenChange(open) }}><DialogContent><DialogHeader><DialogTitle>Kart envanteri</DialogTitle><DialogDescription>Kullanımdaki kartların operasyonel ataması burada değiştirilemez.</DialogDescription></DialogHeader>{value && <><label><span className="mb-1 block text-xs font-medium">Kart numarası</span><Input autoFocus disabled={value.status === "IN_USE"} value={value.cardNumber} onChange={(event) => setDraft({ ...value, cardNumber: event.target.value })} /></label><label><span className="mb-1 block text-xs font-medium">Durum</span><select className="h-9 w-full rounded-md border bg-card px-3 text-sm" value={value.status} disabled={entity?.status === "IN_USE"} onChange={(event) => setDraft({ ...value, status: event.target.value as VisitorCardInventoryItem["status"] })}>{visitorCardStatuses.map((status) => <option key={status} value={status}>{visitorCardStatusLabels[status]}</option>)}</select></label>{value.assignedVisitorName && <p className="text-xs text-slate-600">Atanmış ziyaretçi: {value.assignedVisitorName}</p>}{error && <p className="text-xs font-medium text-red-700" role="alert">{error}</p>}</>}<DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>İptal</Button><Button onClick={() => void save()}>Kaydet</Button></DialogFooter></DialogContent></Dialog> }
function RuleDialog({ open, onOpenChange, onSaved }: { open: boolean; onOpenChange(open: boolean): void; onSaved(): void }) { const [content, setContent] = useState(""); const save = async () => { if (!content.trim()) return; await adminService.publishVisitorRule(content); setContent(""); onSaved(); onOpenChange(false) }; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Yeni kural versiyonu</DialogTitle><DialogDescription>Yayınlandığında mevcut aktif kural korunur ve bu metin yeni aktif versiyon olur.</DialogDescription></DialogHeader><label><span className="mb-1 block text-xs font-medium">Kural metni</span><Textarea value={content} onChange={(event) => setContent(event.target.value)} rows={7} /></label><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>İptal</Button><Button disabled={!content.trim()} onClick={() => void save()}>Yeni versiyonu yayınla</Button></DialogFooter></DialogContent></Dialog> }
