import type { RefObject } from "react"

import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { getGoodsDirectionLabel, getGoodsMovementDisplayStatus, type GoodsMovement } from "@/domain/goods-movements"
import { GOODS_REPORT_STATUS_LABELS } from "@/features/reports/goods-report-utils"
import { formatTr } from "@/lib/date"

export function GoodsMovementDetailDialog({ movement, open, onOpenChange, returnFocusRef }: { movement: GoodsMovement | null; open: boolean; onOpenChange(open: boolean): void; returnFocusRef: RefObject<HTMLTableRowElement | null> }) {
  if (!movement) return null
  const status = getGoodsMovementDisplayStatus(movement)
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="!w-[min(640px,calc(100vw-2rem))] !max-w-none gap-0 overflow-hidden p-0" aria-describedby={undefined} onCloseAutoFocus={(event) => { event.preventDefault(); returnFocusRef.current?.focus() }}><DialogHeader className="border-b bg-white px-5 py-4 pr-12"><DialogTitle className="text-base font-semibold text-slate-900">Mal Hareketi Detayı</DialogTitle><p className="text-xs text-slate-500">{formatTr(new Date(`${movement.plannedDate}T12:00:00`), "d MMMM yyyy")} · {getGoodsDirectionLabel(movement.direction)}</p></DialogHeader><div className="max-h-[min(70vh,560px)] overflow-y-auto px-5 py-4"><section className="border-b border-slate-100 pb-4"><h3 className="mb-2 text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500">Hareket</h3><dl className="grid gap-2.5 sm:grid-cols-2"><Field label="Yön" value={getGoodsDirectionLabel(movement.direction)} /><Field label="Durum" value={<StatusPill status={status} />} /><Field label="Karşı taraf" value={movement.counterpartyName} /><Field label="Mal / açıklama" value={movement.goodsDescription} /></dl></section><div className="grid gap-4 py-4 sm:grid-cols-2 sm:divide-x sm:divide-slate-200"><section className="space-y-2.5 sm:pr-5"><h3 className="text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500">Organizasyon</h3><dl className="space-y-2.5"><Field label="Şirket" value={movement.companyName} /><Field label="Tesis" value={movement.facilityName} /><Field label="Referans no" value={movement.referenceNumber ?? "—"} /></dl></section><section className="space-y-2.5 border-t border-slate-100 pt-4 sm:border-t-0 sm:pl-5 sm:pt-0"><h3 className="text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500">Zaman ve gerçekleşme</h3><dl className="space-y-2.5"><Field label="Planlanan tarih" value={formatTr(new Date(`${movement.plannedDate}T12:00:00`), "d MMMM yyyy")} /><Field label="Planlanan saat" value={movement.plannedTime ?? "—"} /><Field label="Gerçekleşen zaman" value={movement.actualAt ? formatTr(new Date(movement.actualAt), "d MMMM yyyy HH:mm") : "—"} /><Field label="Gerçekleşen plaka" value={movement.actualPlate ?? "—"} /><Field label="Gerçekleşen şoför" value={movement.actualDriverName ?? "—"} /></dl></section></div>{movement.note && <section className="border-t border-slate-100 pt-4"><h3 className="mb-2 text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500">Not</h3><p className="whitespace-pre-wrap text-[13px] text-slate-900">{movement.note}</p></section>}</div></DialogContent></Dialog>
}

function Field({ label, value }: { label: string; value: React.ReactNode }) { return <div className="grid grid-cols-[118px_minmax(0,1fr)] gap-2 text-[13px]"><dt className="text-slate-500">{label}</dt><dd className="min-w-0 break-words font-medium text-slate-900">{value}</dd></div> }
function StatusPill({ status }: { status: ReturnType<typeof getGoodsMovementDisplayStatus> }) { const className = status === "LATE" ? "border-amber-200 bg-amber-50 text-amber-700" : status === "COMPLETED" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : status === "CANCELLED" ? "border-slate-200 bg-slate-100 text-slate-600" : "border-blue-200 bg-blue-50 text-blue-700"; return <span className={`inline-flex rounded-full border px-1.5 py-0.5 text-[10px] font-medium ${className}`}>{GOODS_REPORT_STATUS_LABELS[status]}</span> }
